log_level: debug
redis:
  address: redis:6379
keys:
  devkey: secret

rtc:
  node_ip: 127.0.0.1
  use_external_ip: false

webhook:
  api_key: devkey
  urls:
      - http://app-dev:8000/api/v1.0/rooms/webhooks-livekit/
